### Numpy
- 데이터는 행렬로 표현
- 행렬 데이터를 빠르게 계산해야 함
- 행렬 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성됨
    - 선형대수학을 빠르게 연상
        - 스칼라, 벡터, 매트릭스

In [1]:
import numpy as np

#### 행렬 데이터 생성
- ndarray : 한 가지 데이터 타입만 값으로 사용이 가능
- ndim : 행렬의 차원
- shape : 행렬의 모양(행의 수, 열의 수)

In [2]:
array = np.array([1, 2, 3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [3]:
array2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]],
)
array2, array2.ndim, array2.shape 

(array([[1, 2, 3],
        [4, 5, 6]]), 2, (2, 3))

#### 행렬의 모양(shape) 바꾸기

In [4]:
array2.reshape(3, 2)  # array2.reshape(3, 2, 1) 3차원으로도 바꾸기 가능

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 행렬 데이터의 선택 : offset index : masking

In [5]:
array2[1][::-1]

array([6, 5, 4])

In [6]:
array2[1, 2]  # array2[1][2]와 같은 표현

6

#### 데이터 수정

In [7]:
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

#### 브로드 캐스팅

In [8]:
array2[0] = 0
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [9]:
array2[0] = [7, 8, 9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [10]:
# 조건으로 선택
idx = array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [11]:
array2[idx] # True에 해당하는 값만 출력

array([ 8,  9, 10])

In [12]:
array2[idx] = 100 # True에 해당하는 값들을 모두 100으로 바꿔주기
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

#### 행렬 데이터의 생성 2

In [13]:
data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
data.dtype

dtype('float64')

In [15]:
data2 = data.astype("int")
data2.dtype

dtype('int32')

In [16]:
data = np.ones((2, 3, 2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(5, 10, 2)

array([5, 7, 9])